@startuml
skinparam shadowing false
title Получение отфильтрованного списка комплексов

start
:Провести валидацию на фронтенде;
:Отправить GET-запрос на Backend Server;
:Провести проверку авторизации и прав доступа;

if (Авторизация по токену пройдена?) then (нет)
    :Вернуть ошибку 401 Unauthorized\nОписание ошибки: “Ошибка авторизации”;
    stop
else (да)
    if (Проверка на права пользователя пройдена?) then (нет)
        :Вернуть ошибку 403  Forbidden.\nОписание ошибки «Недостаточно прав для совершения действия».;
        stop
    else (да)    
        :Извлечь параметры фильтрации из запроса;

    if (Отсутствуют параметры фильтрации?) then (да)
        :Вернуть ошибку 400 Bad Request\nОписание ошибки: “Задайте параметры фильтрации”;
        stop
    else (нет)
        :Провести валидацию данных\nзаполненных полей;

        if (Валидация на типы данных пройдена?) then (нет)
            :Вернуть ошибку 400 Bad Request\nОписание ошибки: “Некорректные данные в поле {название поля}”;
            stop
        else (да)
            if (Выбраны критерии фильтрации change_date, public_date?) then (да)
                if (Значение change_date, public_date больше текущей даты?) then (да)
                    :Вернуть ошибку 400 Bad Request\nОписание ошибки: “Дата изменения/дата публикации не может быть больше текущей даты”;
                    stop
                else (нет)
                endif
            else (нет)
            endif

            
            :Направить SELECT-запрос к таблице COMPLEXES базы данных\nна получение списка комплексов;

            if (Сервер базы данных ответил в течение 30 секунд?) then (нет)
                :Вернуть ошибку 504 Gateway Timeout;
                stop
            else (да)
                :Проверить полученный результат на наличие комплексов,\nсоответствующих критериям фильтрации;

                if (Есть комплексы, соответствующие критериям фильтрации?) then (нет)
                    :Вернуть ошибку 404 Not Found\nОписание ошибки: “Поиск не дал результатов”;
                    stop
                else (да)
                    :Вернуть JSON-ответ со списком комплексов\n и успешным статусом ответа 200 OK;
                    stop
                endif
            endif
        endif
    endif
endif
@enduml